### PR TITLE
chore(README.md, build.gradle): updates to major version

### PR DESCRIPTION
**Pull request by joaoaab**
## Proposed changes

This PR bumps the version to a new major, called 2.0.0
This version is up to date and working with version 2.187.0 of the api
## Checklist
- [X] Style check and tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by gaabs — APPROVED** [review]

**Review by figueredo — COMMENTED** [review]
Could you detail which are the breaking changes that make it a major bump?

**Comment by joaoaab** [comment]
> Could you detail which are the breaking changes that make it a major bump?

Sure, the number of methods would have to increase a lot to cover all the use cases of the transactions route with the current approach (overloading methods), so i changed the input approach to be a builder-based input dto, so it makes it breaking.

Also, to take advantage of this bump to a major, we changed the package structured (we had none, it was all in one package), to a package by feature style, making it easier to find what you're looking for while implementing your solution using this lib.

**Comment by joaoaab** [comment]
> > Could you detail which are the breaking changes that make it a major bump?
> 
> Sure, the number of methods would have to increase a lot to cover all the use cases of the transactions route with the current approach (overloading methods), so i changed the input approach to be a builder-based input dto, so it makes it breaking.
> 
> Also, to take advantage of this bump to a major, we changed the package structured (we had none, it was all in one package), to a package by feature style, making it easier to find what you're looking for while implementing your solution using this lib.

if you wanna know more, please read PR #57 and #55

**Comment by figueredo** [comment]
Nice, thanks! This needs to be merged after https://github.com/inloco/incognia-api-java/pull/57, right?

**Review by figueredo — APPROVED** [review]

**Pull request merged**
